# The main pipeline for the TPCH pipeline
resources:
  pipelines:
    tpch_ingestion_pipeline:
      name: "TPCH Ingestion Pipeline"
      serverless: true
      channel: preview
      catalog: ${var.catalog}
      target: tpch
      libraries:
        - notebook:
            path: ../../pipelines/tpch/tpch_pipeline.ipynb

      # configuration:
      #   bundle.sourcePath: /Workspace/${workspace.file_path}/src
