# The main job for the sales_order pipeline
resources:
  jobs:
    sales_orders_ingestion_job:
      name: sales_orders_ingestion_job
      schedule:
        # Run every day at 8:37 AM MST
        quartz_cron_expression: "44 37 8 * * ?"
        timezone_id: America/Boise

      email_notifications:
        on_failure:
          - guanjie.shen@databricks.com
      tags:
        envionment: ${var.env}
        
      parameters:
        - name: catalog
          default: ${var.catalog}
        - name: schema
          default: sales_orders

      tasks:
        - task_key: orders_raw
          sql_task:
            warehouse_id: ${var.warehouse_id}
            file:
              path: ../../pipelines/sales_orders/sales_orders_pipeline.sql
